version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fcmarkt-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fcmarkt
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
